version: '3.4'
services:
  scraper:
    image: bytes85/php7.4-cli
    volumes:
      - ./:/scraper
      - ./docker/configs/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    entrypoint: ["php", "-d", "memory_limit=-1", "/scraper/bin/application.php", "app:run-scraper"]