# app/config/services.yaml

# Some retrievable parameters
parameters:
  baseUrl: 'https://www.walmart.com'
  allCategories:
    url: '/all-departments'
    linksSelector: 'div.alldeps-DepartmentLinks-columnList a.alldeps-DepartmentLinks-categoryList-categoryLink'
  items:
    linksSelector: 'div.search-result-gridview-item'
    card:
      title: 'a.product-title-link'
      price: 'span.price-main span.visuallyhidden'
      soldBy: 'span.marketplace-sold-by-company-name'
      rating: 'span.seo-avg-rating'

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface:
    class: 'Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface'
    factory: ['@service_container', 'getParameterBag' ]

  App\Command\ScraperCommand:
    class: 'App\Command\ScraperCommand'
    arguments:
      $parameters: '@Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface'
      $logger: '@Monolog\Logger'
      $phantomJS: '@App\Service\PhantomJS'
      $name: 'app:run-scraper'

  Monolog\Handler\StreamHandler:
    class: 'Monolog\Handler\StreamHandler'
    arguments:
      $stream: 'php://stderr'

  Monolog\Logger:
    class: 'Monolog\Logger'
    arguments:
      $name: 'app'
    calls:
      - [ pushHandler, ['@Monolog\Handler\StreamHandler'] ]

  PhantomInstaller\PhantomBinary:
    class: 'PhantomInstaller\PhantomBinary'

  App\Service\PhantomJS:
    class: 'App\Service\PhantomJS'
    arguments:
      $binary: '@PhantomInstaller\PhantomBinary'
      $crawler: '@Symfony\Component\DomCrawler\Crawler'
      $baseUrl: '%baseUrl%'

  Symfony\Component\DomCrawler\Crawler:
    class: 'Symfony\Component\DomCrawler\Crawler'